# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x01\n\nUserAction\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x62oardgame_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63tion_value\x18\x04 \x01(\x01\x12/\n\x0b\x61\x63tion_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"7\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"\xfe\x01\n\tBoardgame\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0bmin_players\x18\x04 \x01(\x05\x12\x13\n\x0bmax_players\x18\x05 \x01(\x05\x12\x15\n\rplay_time_min\x18\x06 \x01(\x05\x12\x15\n\rplay_time_max\x18\x07 \x01(\x05\x12\x12\n\ncategories\x18\x08 \x01(\t\x12\x12\n\nrating_avg\x18\t \x01(\x01\x12\x14\n\x0crating_count\x18\n \x01(\x05\x12\x18\n\x10popularity_score\x18\x0b \x01(\x01\x12\x11\n\timage_url\x18\x0c \x01(\t\"G\n\x16RecommendationResponse\x12-\n\nboardgames\x18\x01 \x03(\x0b\x32\x19.recommendation.Boardgame\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"B\n\x11\x42oardgamesRequest\x12-\n\nboardgames\x18\x01 \x03(\x0b\x32\x19.recommendation.Boardgame2\x96\x02\n\x15RecommendationService\x12\x46\n\x0eSendUserAction\x12\x1a.recommendation.UserAction\x1a\x18.recommendation.Response\x12\x63\n\x12GetRecommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\x12P\n\x11SendAllBoardgames\x12!.recommendation.BoardgamesRequest\x1a\x18.recommendation.ResponseB\x10Z\x0eguru-game/gRPCb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016guru-game/gRPC'
  _globals['_USERACTION']._serialized_start=74
  _globals['_USERACTION']._serialized_end=217
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=219
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=274
  _globals['_BOARDGAME']._serialized_start=277
  _globals['_BOARDGAME']._serialized_end=531
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=533
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=604
  _globals['_RESPONSE']._serialized_start=606
  _globals['_RESPONSE']._serialized_end=650
  _globals['_BOARDGAMESREQUEST']._serialized_start=652
  _globals['_BOARDGAMESREQUEST']._serialized_end=718
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=721
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=999
# @@protoc_insertion_point(module_scope)
