// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: recommendation.proto

package gRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BoardgameId   string                 `protobuf:"bytes,2,opt,name=boardgame_id,json=boardgameId,proto3" json:"boardgame_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`      // เช่น "like", "favorite", "play_time"
	ActionValue   float64                `protobuf:"fixed64,4,opt,name=action_value,json=actionValue,proto3" json:"action_value,omitempty"` // เช่น เวลาที่เล่น หรือ 1.0 สำหรับ like
	ActionTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=action_time,json=actionTime,proto3" json:"action_time,omitempty"`      // เวลาที่กระทำกิจกรรม
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAction) Reset() {
	*x = UserAction{}
	mi := &file_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAction) ProtoMessage() {}

func (x *UserAction) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAction.ProtoReflect.Descriptor instead.
func (*UserAction) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *UserAction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAction) GetBoardgameId() string {
	if x != nil {
		return x.BoardgameId
	}
	return ""
}

func (x *UserAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *UserAction) GetActionValue() float64 {
	if x != nil {
		return x.ActionValue
	}
	return 0
}

func (x *UserAction) GetActionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ActionTime
	}
	return nil
}

type RecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // จำนวนรายการแนะนำ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	mi := &file_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Boardgame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MinPlayers      int32                  `protobuf:"varint,4,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers      int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	PlayTimeMin     int32                  `protobuf:"varint,6,opt,name=play_time_min,json=playTimeMin,proto3" json:"play_time_min,omitempty"`
	PlayTimeMax     int32                  `protobuf:"varint,7,opt,name=play_time_max,json=playTimeMax,proto3" json:"play_time_max,omitempty"`
	Categories      string                 `protobuf:"bytes,8,opt,name=categories,proto3" json:"categories,omitempty"`
	RatingAvg       float64                `protobuf:"fixed64,9,opt,name=rating_avg,json=ratingAvg,proto3" json:"rating_avg,omitempty"`
	RatingCount     int32                  `protobuf:"varint,10,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	PopularityScore float64                `protobuf:"fixed64,11,opt,name=popularity_score,json=popularityScore,proto3" json:"popularity_score,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Boardgame) Reset() {
	*x = Boardgame{}
	mi := &file_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Boardgame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boardgame) ProtoMessage() {}

func (x *Boardgame) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boardgame.ProtoReflect.Descriptor instead.
func (*Boardgame) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *Boardgame) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Boardgame) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Boardgame) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Boardgame) GetMinPlayers() int32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *Boardgame) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *Boardgame) GetPlayTimeMin() int32 {
	if x != nil {
		return x.PlayTimeMin
	}
	return 0
}

func (x *Boardgame) GetPlayTimeMax() int32 {
	if x != nil {
		return x.PlayTimeMax
	}
	return 0
}

func (x *Boardgame) GetCategories() string {
	if x != nil {
		return x.Categories
	}
	return ""
}

func (x *Boardgame) GetRatingAvg() float64 {
	if x != nil {
		return x.RatingAvg
	}
	return 0
}

func (x *Boardgame) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *Boardgame) GetPopularityScore() float64 {
	if x != nil {
		return x.PopularityScore
	}
	return 0
}

func (x *Boardgame) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type RecommendationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boardgames    []*Boardgame           `protobuf:"bytes,1,rep,name=boardgames,proto3" json:"boardgames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationResponse) Reset() {
	*x = RecommendationResponse{}
	mi := &file_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResponse) ProtoMessage() {}

func (x *RecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResponse.ProtoReflect.Descriptor instead.
func (*RecommendationResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendationResponse) GetBoardgames() []*Boardgame {
	if x != nil {
		return x.Boardgames
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BoardgamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boardgames    []*Boardgame           `protobuf:"bytes,1,rep,name=boardgames,proto3" json:"boardgames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardgamesRequest) Reset() {
	*x = BoardgamesRequest{}
	mi := &file_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardgamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardgamesRequest) ProtoMessage() {}

func (x *BoardgamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardgamesRequest.ProtoReflect.Descriptor instead.
func (*BoardgamesRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *BoardgamesRequest) GetBoardgames() []*Boardgame {
	if x != nil {
		return x.Boardgames
	}
	return nil
}

var File_recommendation_proto protoreflect.FileDescriptor

const file_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x14recommendation.proto\x12\x0erecommendation\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\n" +
	"UserAction\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fboardgame_id\x18\x02 \x01(\tR\vboardgameId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\faction_value\x18\x04 \x01(\x01R\vactionValue\x12;\n" +
	"\vaction_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"actionTime\"F\n" +
	"\x15RecommendationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x87\x03\n" +
	"\tBoardgame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vmin_players\x18\x04 \x01(\x05R\n" +
	"minPlayers\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\x12\"\n" +
	"\rplay_time_min\x18\x06 \x01(\x05R\vplayTimeMin\x12\"\n" +
	"\rplay_time_max\x18\a \x01(\x05R\vplayTimeMax\x12\x1e\n" +
	"\n" +
	"categories\x18\b \x01(\tR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"rating_avg\x18\t \x01(\x01R\tratingAvg\x12!\n" +
	"\frating_count\x18\n" +
	" \x01(\x05R\vratingCount\x12)\n" +
	"\x10popularity_score\x18\v \x01(\x01R\x0fpopularityScore\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\"S\n" +
	"\x16RecommendationResponse\x129\n" +
	"\n" +
	"boardgames\x18\x01 \x03(\v2\x19.recommendation.BoardgameR\n" +
	"boardgames\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x11BoardgamesRequest\x129\n" +
	"\n" +
	"boardgames\x18\x01 \x03(\v2\x19.recommendation.BoardgameR\n" +
	"boardgames2\x96\x02\n" +
	"\x15RecommendationService\x12F\n" +
	"\x0eSendUserAction\x12\x1a.recommendation.UserAction\x1a\x18.recommendation.Response\x12c\n" +
	"\x12GetRecommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\x12P\n" +
	"\x11SendAllBoardgames\x12!.recommendation.BoardgamesRequest\x1a\x18.recommendation.ResponseB\x10Z\x0eguru-game/gRPCb\x06proto3"

var (
	file_recommendation_proto_rawDescOnce sync.Once
	file_recommendation_proto_rawDescData []byte
)

func file_recommendation_proto_rawDescGZIP() []byte {
	file_recommendation_proto_rawDescOnce.Do(func() {
		file_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_proto_rawDesc), len(file_recommendation_proto_rawDesc)))
	})
	return file_recommendation_proto_rawDescData
}

var file_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_recommendation_proto_goTypes = []any{
	(*UserAction)(nil),             // 0: recommendation.UserAction
	(*RecommendationRequest)(nil),  // 1: recommendation.RecommendationRequest
	(*Boardgame)(nil),              // 2: recommendation.Boardgame
	(*RecommendationResponse)(nil), // 3: recommendation.RecommendationResponse
	(*Response)(nil),               // 4: recommendation.Response
	(*BoardgamesRequest)(nil),      // 5: recommendation.BoardgamesRequest
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_recommendation_proto_depIdxs = []int32{
	6, // 0: recommendation.UserAction.action_time:type_name -> google.protobuf.Timestamp
	2, // 1: recommendation.RecommendationResponse.boardgames:type_name -> recommendation.Boardgame
	2, // 2: recommendation.BoardgamesRequest.boardgames:type_name -> recommendation.Boardgame
	0, // 3: recommendation.RecommendationService.SendUserAction:input_type -> recommendation.UserAction
	1, // 4: recommendation.RecommendationService.GetRecommendations:input_type -> recommendation.RecommendationRequest
	5, // 5: recommendation.RecommendationService.SendAllBoardgames:input_type -> recommendation.BoardgamesRequest
	4, // 6: recommendation.RecommendationService.SendUserAction:output_type -> recommendation.Response
	3, // 7: recommendation.RecommendationService.GetRecommendations:output_type -> recommendation.RecommendationResponse
	4, // 8: recommendation.RecommendationService.SendAllBoardgames:output_type -> recommendation.Response
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_recommendation_proto_init() }
func file_recommendation_proto_init() {
	if File_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_proto_rawDesc), len(file_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_proto_goTypes,
		DependencyIndexes: file_recommendation_proto_depIdxs,
		MessageInfos:      file_recommendation_proto_msgTypes,
	}.Build()
	File_recommendation_proto = out.File
	file_recommendation_proto_goTypes = nil
	file_recommendation_proto_depIdxs = nil
}
